workflows:
  build-ios:
    name: Build iOS IPA
    environment:
      node: v18
      groups:
        - expo_credentials
    scripts:
      - name: Install dependencies
        script: |
          node --version
          npm --version
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli@latest
      - name: Build iOS IPA
        script: |
          eas build --platform ios --profile simulator
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - tinchantcamille@outlook.com
